root: /mnt/files

identity: alice

key: /mnt/files/keys/alice.pri

keepers:
  - alice
  - bob

teams:
  team-1:
    - bob
    - frank
  team-2:
    - alice
    - dave
    - erin
    - grace
  team-3:
    - chuck
    - dave

tags: |
  {
    "type": "object",
    "required": [
      "type"
    ],
    "properties": {
      "type": {
        "type": "string",
        "enum": ["ACME", "Globex", "Hooli"]
      }
    },
    "additionalProperties": true
  }

permissions:
  - uri ~ '^foo/':
      - +team-1
  - uri ~ '^foo/bar/lorem ipsum\.txt$' && tags.type != 'ACME':
      - -team-1
      - +chuck

templates:
  - uri ~ '\.login$': login
  - uri ~ '\.host$': host
