root: /mnt/files

key: /mnt/files/keys/alice.pri

keepers:
  - alice
  - bob

teams:
  all:
    - alice
    - bob
    - chuck
    - dave
    - erin
    - frank
    - grace
  team-1:
    - bob
    - frank
  team-2:
    - alice
    - dave
    - erin
    - grace
  team-3:
    - chuck
    - dave

permissions:
  - uri ~ '^foo/':
      - +team-1
  - uri ~ '^foo/bar/lorem ipsum\.txt$' && tags.type != 'acme':
      - -team-1
      - +chuck

templates:
  - uri ~ '\.login$': login

  - uri ~ '\.host$': host
