name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Execute CI stuff & push code coverage
        run: |
          make ci
          bash <(curl -s https://codecov.io/bash) -t ed11b3fa-195a-458b-b428-1884ce416687
